
* Personal Modules for Visual Molecular Dynamics (VMD)

** Installation

The plugins will need to be copied or linked into the appropriate
plugins folder.

In the ~${VMDDIR}/plugins~ folder there is a few folders:

- include :: header files for plugins
- arch (e.g. LINUXAMD64) :: this could be different and is
  your architecture, this is where the compiled plugins go. This also
  will have Tcl/Python scripts which are used with the compiled
  plugins.
- noarch :: Pure Tcl/Python plugins, these don't require any compiled
  part.

For now we are just looking at the *noarch* section which has these
subfolders:

- tcl
- python

For obvious reasons.

The best solution is to just add the load path for a collection of
plugins in your startup script:

#+begin_src tcl
  lappend auto_path $env(VMD_SHARED_PLUGINS)/noarch/tcl
#+end_src

*** A Suggestion On Configuration

I load plugins from different places and not just my own.

Instead of plopping them down right into the installed ~VMDDIR~ I put
them in a shared location and then I just have a single script which
links and expects that location.

This just keeps things cleaner and doesn't put paths depending on your
dev repos and is persistent if you need to quickly reinstall VMD for
whatever reason.

The gist is that I want to download a script I set up a directory
~VMD_SHARED_PLUGINS~

#+begin_src sh
export VMD_SHARED_PLUGINS="$HOME/.local/share/vmd_shared_plugins"
mkdir -p "${VMD_SHARED_PLUGINS}"/noarch/{tcl,python}
#+end_src

Then you'll download the plugins to there, rather than the VMD
installation ~VMDDIR~.

** Loading Plugins

Then to be able to use the plugins you'll have to run some commands at
the console or in your ~.vmdrc~.

*** Tcl

For each plugin this might differ depending on whether there is a GUI
to configure or not.

You can always load the functions/procs into the Tcl terminal
environment like this:

#+begin_src tcl
  package require packagename
#+end_src

There are two ways to add the menu, the latter is supposed to be the
"right way":

#+begin_src tcl
  menu tk register "Group/Extension Name" packagename
#+end_src

The second way you need to know the proc for it to call:


#+begin_src tcl
  vmd_install_extension packagename packagename_tk "Group/Extension Name"
#+end_src

For these plugins just see the vmd script ~load_plugins.tcl~ to load
them all.

** Plugins

*** Tcl

- textview :: an example project showing how to make a plugin.

*** Python

- emptywindow :: an example project just to show a window.
